drop table if exists OPERATION;
drop table if exists ACCOUNT;
drop table if exists CLIENT;

create table CLIENT(
                       id bigint generated by default as identity,
                       username varchar(255),
                       password varchar(255),
                       primary key (id)
);

CREATE TABLE ACCOUNT (
                         id bigint generated by default as identity,
                         account_balance double not null,
                         account_number integer not null,
                         client_id bigint,
                         primary key (id)
);

create table OPERATION(
                          id bigint generated by default as identity,
                          balance double,
                          date DATETIME,
                          operation_type varchar(255),
                          operation_value double,
                          account_id bigint,
                          primary key (id)
);

alter table account   add constraint UK_66gkcp94endmotfwb8r4ocxm9 unique (account_number);
alter table account  add constraint FKkm8yb63h4ownvnlrbwnadntyn   foreign key (client_id) references client;
alter table operation   add constraint FKloy20r01mn4truqqu460w3j9q  foreign key (account_id)  references account;
